<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DELLi310GEN" failures="1" tests="1" name="LoginPage Module(failed)" time="4.277" errors="0" timestamp="2022-05-31T09:06:09 IST">
  <testcase classname="testNGScripts.LoginModule" name="TC4_RESET" time="0.321">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testNGScripts.LoginModule.TC4_RESET(LoginModule.java:62)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TC4_RESET -->
  <testcase classname="testNGScripts.LoginModule" name="TC1_Login" time="0.0">
    <ignored/>
  </testcase> <!-- TC1_Login -->
  <testcase classname="testNGScripts.LoginModule" name="TC3_InvalidLogin" time="0.0">
    <ignored/>
  </testcase> <!-- TC3_InvalidLogin -->
  <testcase classname="testNGScripts.LoginModule" name="TC2_Logout" time="0.0">
    <ignored/>
  </testcase> <!-- TC2_Logout -->
</testsuite> <!-- LoginPage Module(failed) -->
